import type { NextPage } from "next";
import Head from "next/head";
import PageShell from "../components/layouts/PageShell";
import { Container, Row, Text } from "@nextui-org/react";
import Header from "../components/layouts/Header";

const Home: NextPage = () => (
  <>
    <Head>
      <title>Danish Shakeel</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <PageShell>
      <Container xs>
        <Row css={{ padding: 20 }}>
          <Header />
        </Row>
        <hr />
        <Row css={{ padding: 20 }}>
          <Text>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry.
          </Text>
        </Row>
      </Container>
    </PageShell>
  </>
);

export default Home;
